import Head from "next/head";
import styles from "@styles/Home.module.css";
import Link from "next/link";
import dynamic from "next/dynamic";
import { useState } from "react";

const HelloComponent = dynamic(() => import("@components/Hello"), {
  loading: () => <p>Loading...</p>,
});

export default function Home() {
  const [isHello, setIsHello] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => setIsHello((isHello) => !isHello)}>
        Show Hello Component
      </button>
      {isHello && <HelloComponent />}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learning <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href="/avatar">
          <a
            style={{
              marginTop: "24px",
              color: "blue",
              fontSize: "20px",
              textDecoration: "underline",
            }}
          >
            Check List Avatar
          </a>
        </Link>
      </main>
    </div>
  );
}
